# Generated by Django 2.0.5 on 2018-05-13 23:23

import ckeditor.fields
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('picture', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
