# Generated by Django 2.0.5 on 2018-05-14 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_auto_20180514_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersite',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
