# Generated by Django 2.0.5 on 2018-05-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_auto_20180514_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersite',
            old_name='name',
            new_name='site_name',
        ),
    ]
