# Generated by Django 2.0.5 on 2018-05-14 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_auto_20180514_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
