# Generated by Django 2.0.5 on 2018-05-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_auto_20180514_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersite',
            old_name='site_name',
            new_name='name',
        ),
    ]
