# Generated by Django 2.0.5 on 2018-05-14 23:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_auto_20180514_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersite',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
