# Generated by Django 2.0.5 on 2018-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_auto_20180514_2351'),
    ]

    operations = [
    ]
