# Generated by Django 2.0.5 on 2018-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0008_auto_20180516_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='organization',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='when_available',
            field=models.TextField(blank=True),
        ),
    ]
