# Generated by Django 2.0.5 on 2018-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0009_auto_20180516_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='sites',
            field=models.ManyToManyField(blank=True, to='map_app.PartnerSite'),
        ),
    ]
