# Generated by Django 2.0.5 on 2018-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0010_auto_20180516_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='organization',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='organization',
            field=models.ManyToManyField(blank=True, to='map_app.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='when_available',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
