# Generated by Django 2.0.5 on 2018-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0011_auto_20180516_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='name',
            field=models.CharField(blank=True, help_text='General categories of interest, such as education, human rights or sustainable agriculture.', max_length=200),
        ),
        migrations.AlterField(
            model_name='haverfordoffice',
            name='name',
            field=models.CharField(blank=True, help_text='Name of office on campus that maintains this partnership.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the partner organization.', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, help_text='Relevant academic disciplines or majors', max_length=200),
        ),
    ]
