# Generated by Django 2.0.5 on 2018-05-18 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0012_auto_20180518_1305'),
    ]

    operations = [
    ]
