# Generated by Django 2.0.5 on 2018-05-18 17:22

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0013_auto_20180518_1420'),
    ]

    operations = [
    ]
