# Generated by Django 2.0.5 on 2018-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0015_auto_20180518_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersite',
            name='when_available',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
