# Generated by Django 2.0.5 on 2018-05-18 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0016_auto_20180518_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haverfordoffice',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
