# Generated by Django 2.0.5 on 2018-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0017_auto_20180518_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ManyToManyField(blank=True, to='map_app.PartnerSite'),
        ),
    ]
