# Generated by Django 2.0.5 on 2018-05-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0019_remove_person_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='contact',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_app.Person'),
        ),
    ]
