# Generated by Django 2.0.5 on 2018-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0020_auto_20180526_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='contact',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='partnersite',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
