# Generated by Django 2.0.5 on 2018-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0021_auto_20180526_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='partnersite',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='contact',
            field=models.ManyToManyField(blank=True, to='map_app.Person'),
        ),
    ]
