# Generated by Django 2.0.5 on 2018-05-31 12:37

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0023_auto_20180531_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='when_available',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
