# Generated by Django 2.0.5 on 2018-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0024_auto_20180531_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersite',
            name='date',
        ),
        migrations.AddField(
            model_name='partnersite',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnersite',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
